/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminProductsRouteImport } from './routes/_admin/products'
import { Route as AdminOrdersRouteImport } from './routes/_admin/orders'
import { Route as AdminLibraryRouteImport } from './routes/_admin/library'
import { Route as AdminCategoriesRouteImport } from './routes/_admin/categories'
import { Route as AdminCartsRouteImport } from './routes/_admin/carts'
import { Route as AdminProductsIndexRouteImport } from './routes/_admin/products.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProductsNewRouteImport } from './routes/_admin/products.new'
import { Route as AdminProductsProductIdRouteImport } from './routes/_admin/products.$productId'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/_admin/products_.$productId.edit'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCartsRoute = AdminCartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products_/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/signin': typeof SigninRoute
  '/carts': typeof AdminCartsRoute
  '/categories': typeof AdminCategoriesRoute
  '/library': typeof AdminLibraryRoute
  '/orders': typeof AdminOrdersRoute
  '/products': typeof AdminProductsRouteWithChildren
  '/users': typeof AdminUsersRoute
  '/products/$productId': typeof AdminProductsProductIdRoute
  '/products/new': typeof AdminProductsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products/': typeof AdminProductsIndexRoute
  '/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/carts': typeof AdminCartsRoute
  '/categories': typeof AdminCategoriesRoute
  '/library': typeof AdminLibraryRoute
  '/orders': typeof AdminOrdersRoute
  '/users': typeof AdminUsersRoute
  '/': typeof AdminIndexRoute
  '/products/$productId': typeof AdminProductsProductIdRoute
  '/products/new': typeof AdminProductsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products': typeof AdminProductsIndexRoute
  '/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/_admin/carts': typeof AdminCartsRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/library': typeof AdminLibraryRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/products': typeof AdminProductsRouteWithChildren
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/products/$productId': typeof AdminProductsProductIdRoute
  '/_admin/products/new': typeof AdminProductsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/products/': typeof AdminProductsIndexRoute
  '/_admin/products_/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/carts'
    | '/categories'
    | '/library'
    | '/orders'
    | '/products'
    | '/users'
    | '/products/$productId'
    | '/products/new'
    | '/api/auth/$'
    | '/products/'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/carts'
    | '/categories'
    | '/library'
    | '/orders'
    | '/users'
    | '/'
    | '/products/$productId'
    | '/products/new'
    | '/api/auth/$'
    | '/products'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/signin'
    | '/_admin/carts'
    | '/_admin/categories'
    | '/_admin/library'
    | '/_admin/orders'
    | '/_admin/products'
    | '/_admin/users'
    | '/_admin/'
    | '/_admin/products/$productId'
    | '/_admin/products/new'
    | '/api/auth/$'
    | '/_admin/products/'
    | '/_admin/products_/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/library': {
      id: '/_admin/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/carts': {
      id: '/_admin/carts'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof AdminCartsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/products/': {
      id: '/_admin/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/products/new': {
      id: '/_admin/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/_admin/products/$productId': {
      id: '/_admin/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/_admin/products_/$productId/edit': {
      id: '/_admin/products_/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCartsRoute: typeof AdminCartsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCartsRoute: AdminCartsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
